### ISSUE TITLE
Highlight on key not working

### ISSUE THREAD

**Issue by grecodavide** [jinh0/eyeliner.nvim#15]
As stated in the title, even with `highlight_on_key = true` in my config I get the highlight constantly.
My config:
```lua
require'eyeliner'.setup {
    highlight_on_key = true
}
```

I'm on `NVIM v0.9.0`, with plugins updated

**Comment by jinh0** [comment]
I haven't tried it on v0.9, I'll take a look. Thanks for the issue!

**Comment by jinh0** [comment]
Hey @grecodavide , sorry for the really late reply. This should be fixed in the latest commit 7c539e91b6608661162617be2a4be3f454e423cb . Let me know if it works!

**Comment by grecodavide** [comment]
Great, now it works :)

As a side note, it still won't work if you put the configuration in `after/plugin`
Thanks for the follow up!

**Comment by jinh0** [comment]
Turns out lazy loading wasn't all completely fixed, I think I found the culprit as explained [here](https://github.com/jinh0/eyeliner.nvim/issues/13#issuecomment-1374978397). The latest commit a2c392703ee591e80a962fe907c7d4ba0bdd593b  should fix this.

Could you see if it works now if you put the configuration in `after/plugin`? Thanks!
