### ISSUE TITLE
feature: allow to show the highlighted characters after pressing `f` or `F`

### ISSUE THREAD

**Issue by lalitmee** [jinh0/eyeliner.nvim#4]
This feature is there in `quick-scope`

**Comment by jinh0** [comment]
Thanks for the feature suggestion! The feature is being developed on the `highlight-after-key` branch. I've made a task list on the drafted pull request regarding what is left to be done.

One issue I'm having is, I don't know what event to listen to if the user quits the operation after the user presses f/F/t/T, i.e., by pressing Escape. Does anyone know how to listen to if the user quits the operation while pending?

Here's the current behaviour (if I press escape, the highlight remains):

https://user-images.githubusercontent.com/40512164/179310089-1e58479f-80e6-4172-b6fb-0583cb3fe601.mov

**Comment by lalitmee** [comment]
@jinh0, why can't we just listen to the kepress `ESC`? I think if we check for the `ESC` key press after any of the trigger keys f/F/t/T, we can cancel the highlight and quit the operation.

Will this work?

**Comment by ggandor** [comment]
> Does anyone know how to listen to if the user quits the operation while pending?

I don't think you can do that without a preliminary step, that is, actually getting user input with `getchar`. You can then exit if the input == `esc`, and else `feedkey`. Beware that, for the moment, that would mean having to display a "fake" cursor (like Leap etc. do), because the cursor moves down to the command line when calling `getchar`.
But the highlight will be cleared on the next CursorMoved/etc. anyway, I guess people can live with that.

**Comment by ggandor** [comment]
My 2 cents about the feature itself: this is almost like a labeled f/t mode, EasyMotion/Hop-style, but even worse, because you don't know beforehand _where_ the highlight will appear, i.e., you cannot keep focusing on your destination. By the time your brain processed the character needed to be pressed, you would have easily reached at least the 3rd, if not the 4th occurrence, doing a simple `fX;;;` to the random character you spotted first.

**Comment by jinh0** [comment]
Hey @lalitmee I've pushed the changes for this feature! Thanks again @ggandor for your help.

**Comment by samhh** [comment]
[Works a treat for me](https://github.com/samhh/dotfiles/commit/47f2af3c2247862a22247696c6ce24ae9b8acaf0), thanks @jinh0!

**Comment by andrewferrier** [comment]
This doesn't seem to be working for me. I am setting `highlight_on_key` to `true` but am still seeing highlights all the time, even before pressing `f`/`t`.

**Comment by jinh0** [comment]
Hey @andrewferrier , can you share your configuration with me?

It should look something like this (for Packer):
```lua
use {
  'jinh0/eyeliner.nvim',
  config = function()
    require'eyeliner'.setup {
      highlight_on_key = true
    }
  end
}
```

Also, I made a typo in the README.md: it should be 'jinh0/eyeliner.nvim', but I accidentally put my local path to the plugin -- 42870391753944e344e624eab8abf3d04af675f8 .

**Comment by andrewferrier** [comment]
@jinh0 yep, that's almost exactly the config I am using:


```
    use({
        "jinh0/eyeliner.nvim",
        config = function()
            require("eyeliner").setup({
                highlight_on_key = true,
            })
        end,
    })
```

Despite this, the keys still get highlighted on the current line (even before I've typed 'f' or 't').

To confirm, I'm using NeoVim 0.7.2 on MacOS and eyeliner commit 428703917539 on the `main` branch.

**Comment by jinh0** [comment]
Huh, I just uninstalled and reinstalled eyeliner and set the same settings, it worked for me.

I'm a little lost in how we can fix this issue, so here's a couple ideas:

1. Does the function even get run? Could you try adding a vim.notify or something to make sure the function even runs?

```lua
  use {
    'jinh0/eyeliner.nvim',
    config = function()
      vim.notify('this works?')
      require'eyeliner'.setup {
        highlight_on_key = true
      }
    end
  }
```

If not, that means that you need to do another `:PackerCompile`.

2. Could you share the output of `:verbose autocmd CursorMoved`? The output of `:verbose map f`? If there's a mapping for f AND there's an autocmd for CursorMoved by eyeliner, then that is really strange.

3. If none of these help, I might try using NeoVim 0.7.2 and see if that might somehow be the issue. I'm on 0.7.0.

**Comment by rowsephx** [comment]
@jinh0 I have the same case as @andrewferrier. I'm also on version 0.7.2.

**Comment by jinh0** [comment]
@rowsephx I still can't reproduce this issue. Could you share your configuration?

**Comment by rowsephx** [comment]
@jinh0, its the same as this:

> ```lua
>   use {
>     'jinh0/eyeliner.nvim',
>     config = function()
>       vim.notify('this works?')
>       require'eyeliner'.setup {
>         highlight_on_key = true
>       }
>     end
>   }
> ```

**Comment by jinh0** [comment]
Hey @rowsephx sorry for this issue! I just updated to 0.7.2 and I still can't replicate it. Firstly, does the notification 'this works?' show up in the first place?

I just added a debug configuration option on the latest version, https://github.com/jinh0/eyeliner.nvim/commit/f13c8a19bd23db6ead7424b29f064279f3546738 , which may isolate where the issue is coming from:

Try this:

```lua
  use {
    'jinh0/eyeliner.nvim',
    config = function()
      vim.notify('this works?')
      require'eyeliner'.setup {
        highlight_on_key = true,
        debug = true
      }
    end
  }
```

This option should trigger a notification that says
```
DEBUG: {
  debug = true,
  highlight_on_key = true
}
```

Thanks for your patience!

**Comment by rowsephx** [comment]
@jinh0, It shows the intended debug messages, and the plugin seems to be working fine now. It's most likely that I forgot to re-compile after adding `highlight_on_key = true`.

And also one thing. `highlight_on_key` doesn't work if config is set asynchronously:
```
use {
    'jinh0/eyeliner.nvim',
    keys = { "t", "T", "f", "F" },
    config = function()
        require'eyeliner'.setup {
            highlight_on_key = true,
        }
    end
}
```

**Comment by jinh0** [comment]
Phew! Hopefully it was just an issue with having to recompile. @andrewferrier is it working for you after recompiling? If so, I will close this issue.

Regarding issues with lazy-loading, thanks for letting me know @rowsephx. I'll get started on that. But for the time being, I want to mention that eyeliner.nvim has a small startup time (0.1 ms in my experience), so it is okay if you don't asynchronously / lazy-load it.

**Comment by YorickPeterse** [comment]
I think the issue here is https://github.com/jinh0/eyeliner.nvim/blob/main/plugin/init.lua. This loads and enables the plugin automatically, meaning that a subsequent `require('eyeliner').setup({ ... })` doesn't do anything. To work around that you have to do something like this:

```lua
let e = require('eyeliner')

e.disable()
e.setup({ ... })
e.enable()
```
